version: "3.8"

services: 

  db:
    container_name: db-container-1
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - wpsite
  
  wp1:
    depends_on: 
      - db
    links:
      - db
    container_name: wp-container-1
    image: wordpress
    restart: always
    ports:
      - '8001:80'
    volumes:
      - wp-data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
    networks:
      - wpsite

  wp2:
    depends_on: 
      - db
    links:
      - db
    container_name: wp-container-2
    image: wordpress
    restart: always
    ports:
      - '8002:80'
    volumes:
      - wp-data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
    networks:
      - wpsite

  wp3:
    depends_on: 
      - db
    links:
      - db
    container_name: wp-container-3
    image: wordpress
    restart: always
    ports:
      - '8003:80'
    volumes:
      - wp-data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
    networks:
      - wpsite

networks:
  wpsite:
  
volumes: 
  wp-data: 
  db-data:
