---
- name: wordpress deployment
  hosts: web
  gather_facts: true
  vars:
    admin_user: esi
  roles:
    - role-0-initial-server
    - role-1-setup-mariadb
    - role-2-setup-proxysql
    - role-3-setup-wordpress

- name: load-balancing
  hosts: lb
  gather_facts: true
  roles:
    - role-4-setup-load-balancer
